mautrix_signal/portal.py

Otherwise the message does not get send at all and we get an Exception.
This happens if (for one reason or another) the message db does not contain the quoted message.

Check if quoted message exists in db

---

mautrix_signal/portal.py

The "clean" method with "power_level_content_override" is not working, so this is the workaround. Looks cleaner that way anyway.

Added ability to change direct chats name and avatar

---

mausignald/errors.py
mausignald/rpc.py
mausignald/signald.py

If the signald socket gets disconnected (e.g., signald restart), we will
now retry reconnecting to the socket forever, with a 5 second wait
between attempts.  We will also retry the initial connect forever if the
socket connection fails on startup.
This change creates a couple "synthetic" RPC events for connect and
disconnect that handlers can be attached to, as well as a NotConnected
exception class.  These should help callers deal with the fact that the
client may not always be connected.
I think creating these synthetic events that aren't triggered by messages from signald may be a little awkward.  But we need some way for library callers to register callbacks for reconnections, and using the existing handler code in rpc.py seems like the cleanest solution to me.  Happy to re-work this …

Automatically reconnect to signald

---

Dockerfile
mautrix_signal/portal.py
requirements.txt

This will download received sticker images directly from Signal via https://github.com/signalstickers/signalstickers-client as signald currently does not provide an attachment for stickers (at least for me and #12)
Fixes #12
Maybe the [better solution](https://gitlab.com/signald/signald/-/issues/113) would be for signald to provide the sticker image, so feel free to discard at will ;)

Provide fallback for sticker image if not supplied by signald

---

mautrix_signal/portal.py

Duplicate 'file' section into 'info.thumbnail_file' in order for iOS to display properly webp images.
It works for stickers and message.
Without this patch, no webp image is displayed on iOS.
This can be removed after a fix on this issue: https://github.com/vector-im/element-ios/issues/4004

Fix iOS bug to display image/webp (stickers, messages)

---

mautrix_signal/__main__.py

Fixes #168 
This should ensure that sync requests made to signald are appropriately staggered to prevent the process from being hit by a thundering herd of requests. At the moment this is hardcoded to 10s.
There is a risk that this will make the profile sync speed lower than advertised in the config, but overall shouldn't be too noticeable for smaller bridges.

Add some jitter to the sync loop

---

mautrix_signal/example-config.yaml
mautrix_signal/portal.py
requirements.txt

- Added new config `homeserver.message_send_checkpoint_endpoint`
- Utilized `send_remote_checkpoint` to report success/failure of messages sent to Signal
Depends on https://github.com/mautrix/python/pull/66

Use message send checkpoints

---

mautrix_signal/commands/auth.py
mautrix_signal/config.py
mautrix_signal/example-config.yaml

Handy for running a linked-devices-only bridge, which Signal treats a lot more liberally.

Make it possible to disable device registration from the config

---

mautrix_signal/signal.py

Signal sends `profileKeyUpdate` messages for individual users. I'm not quite sure what these messages represent, but they cause the bridge to create DM rooms unnecessarily.

signal: ignored profile key updates

---

mausignald/signald.py

The only exception is when the message fails to send to anyone in the group.

mausignald/signald: make unregisteredFailures non-fatal

---

mautrix_signal/__main__.py
mautrix_signal/config.py
mautrix_signal/db/__init__.py
mautrix_signal/db/disappearing_message.py
mautrix_signal/db/portal.py
mautrix_signal/db/upgrade.py
mautrix_signal/example-config.yaml
mautrix_signal/matrix.py
mautrix_signal/portal.py
mautrix_signal/signal.py
requirements.txt

When a message is sent or recieved in a Signal chat that has disappearing messages enabled, it will automatically be redacted by the bridge after the time configured on the room. However, note that the countdown timer will only start once the room has been read.
The main mechanism for this is using async functions that just wait the configured number of seconds before redacting. However, there we also store all of the state necessary for determining when to redact a message in the database in case a restart occurs. In the event of a restart, we can resume waiting for the expiration (or redact immediately if we are past the expiration timestamp).
This change also adds m.notice notifications for the user when the disappearing messages setting changes on the Signal chat.

disappearing messages: add support for both inbound and outbound

---

mausignald/signald.py
mausignald/types.py
mautrix_signal/signal.py

**Depends on:** https://gitlab.com/signald/signald/-/merge_requests/115
Sometimes, signald asks for a resend and in those cases, we don't want to show any error.

inbound error messages: show errors after a delay

---

mausignald/errors.py
mautrix_signal/portal.py

Note that is MB, not MiB.
Requires https://gitlab.com/signald/signald/-/commit/9dd4b1bdde9fb77f872a48ae225b3894e54e7ea6
This also makes AttachmentTooLargeError errors report `UNSUPPORTED` checkpoint status instead of `PERM_FAILURE`:
```
{
"checkpoints": [
{
"event_id": "$Jxs4LnDGVLBB5mGgL6cYFIYWXV0mghQj-stpArWlyMk",
"room_id": "!qHOnpPioZRtUoyxqds:localhost",
"step": "REMOTE",
"timestamp": 1644297992431,
"status": "UNSUPPORTED",
"event_type": "m.room.message",
"reported_by": "BRIDGE",
"retry_num": 0,
"message_type": "m.file",
"info": "File is over the 100MB limit."
}
]
}
```

errors: add AttachmentTooLargeError for attachments over 100MB

---

mausignald/errors.py
mausignald/signald.py
mautrix_signal/commands/auth.py
mautrix_signal/user.py
mautrix_signal/web/provisioning_api.py

signald's InternalError exception is meant to be a fallback when unexpected behavior occurs. We were parsing it out in several places which have now been converted into proper protocol errors on the signald side

Stop parsing InternalErrors

---

mautrix_signal/example-config.yaml
mautrix_signal/portal.py
mautrix_signal/puppet.py
requirements.txt

note that I didn't make the QR code upload async when using the bot commands

async media: add ability to upload media asynchronously

---

mausignald/errors.py
mautrix_signal/commands/auth.py
mautrix_signal/commands/signal.py
mautrix_signal/util/__init__.py
mautrix_signal/util/normalize_number.py
mautrix_signal/web/provisioning_api.py

The start new PM endpoint allows you to create PMs with a Signal-registered phone number.
Example usage:
```
curl -X POST \
-H 'Authorization: Bearer PROVISIONING_TOKEN_HERE' \
'http://your.matrix.server.url/_matrix/provision/v2/pm/+11234567890?user_id=@test:localhost'
```
The list contacts endpoint allows you to list contacts for your Signal user:
Example usage:
```
curl -X GET \
-H 'Authorization: Bearer PROVISIONING_TOKEN_HERE' \
'http://your.matrix.server.url/_matrix/provision/v2/contacts?user_id=@test:localhost'
```

provisioning api: add start new PM and list contacts endpoints

---

mautrix_signal/web/provisioning_api.py

```
$ curl 'http://localhost:29328/_matrix/provision/v2/resolve_identifier/11234567890?user_id=@sumner:localhost' -H 'Authorization: Bearer XXXXXXX'
{"error": "Phone number must be entered in international format"}
```

resolve identifier: fix error when phone number entered incorrectly

---

ROADMAP.md
mautrix_signal/matrix.py
mautrix_signal/portal.py

Tested with Signal only user and matrix user logged into the bridge

Invite member

---

mausignald/signald.py
mautrix_signal/matrix.py
mautrix_signal/portal.py

make Signal role ADMINISTRATOR if power level >= 50
make Signal role DEFAULT if power level <50
bridge `invite` and `state_default` upon explicit changes
works for group creation, invites or explicit power level changes

add support for matrix -> signal power level changes

---

mautrix_signal/portal.py

Fixes #258
for logged-in users:
for DEFAULT, the power level is between 0 and 49
for ADMINISTRATOR, the power level is >50
The bot will only change the power level if it is outside those ranges.
for signal puppets, nothing changes.
If the current power level of the user is higher than that of the bridge bot, don't attempt to change it. While the power level may have to be changed, it's pointless to try.
Likewise, if the bot power level is <50, it won't be able to do anything useful and it's pointless to try. We already print a warning for that.
This PR avoids conflicts with other bridges trying to set different power levels (pl 75 is default for the group creator in telegram, in whatsapp it's 95). It will also allow setting power levels even if they can't be set for some users. …

tolerate ranges of power levels for logged-in users to avoid conflicts

---

mausignald/errors.py
mautrix_signal/portal.py

currently, a ProfileUnavailableError will cause _update_participants to fail and groups won't update properly. This PR catches the Error so the remainder of _update_participants can execute.

catch ProfileUnavailableError in _update_participants

---

mautrix_signal/portal.py

This PR bridges kick/invite with correct metadata
- changes detected by sync/restart are performed by the bridge bot. Otherwise:
- invites are always performed by the correct puppet
- kicks are preferably performed by the correct puppet. If the user/puppet that is being kicked is an `ADMINISTRATOR`, then they can be kicked on Signal, but kicking users with equal power level is not permitted on matrix. In that case the kick is performed by bridge bot, with the sender given in the reason.
- The reason for kicking is now formulated to address everyone, not just the person being kicked (previously: "xyz kicked you", "you are not a member..."
- Only leaves are bridged as leaves.
If `levels.invite`>50, then signal `ADMINISTRATOR`s are still able to invite users, the invite is then bridged by …

bridge kick/invite/leave from Signal to Matrix with correct sender

---

ROADMAP.md
mausignald/signald.py
mausignald/types.py
mautrix_signal/matrix.py
mautrix_signal/portal.py

Seems to work just fine.
We might have to think about power levels for kicking/banning/unbanning, because on signal, an `ADMINISTRATOR` can perform those actions on another `ADMINISTRATOR`, whereas matrix does not allow this if power levels are the same. I was thinking we could give a power level of 51 to matrix users, so they will be able to kick puppets, while Signal users can kick matrix users through the bridge bot.

add support for kick/ban/unban

---

mausignald/types.py
mautrix_signal/config.py
mautrix_signal/example-config.yaml
mautrix_signal/portal.py
mautrix_signal/signal.py

Make use of the GroupChange instead of scanning the group info for changes. This should be more efficient and also makes it easier to bridge changes with correct sender metadata. It will also avoid the issue of a particular change being wrongfully bridged as coming from a particular user when a previous change was missed (due to the bridge being down for example).
This should allow removing sender info from `update_info` and most of the functions it calls, but I haven't done that yet, because those would mean a lot of changes in a lot of places. I would also incorporate the `GroupV2ID` type into `GroupV2`. So far I have only incorporated minimal changes into the rest of the code to make it work with the new additions. The aforementioned changes are better saved for another PR or another …

use group change

---

ROADMAP.md
mautrix_signal/config.py
mautrix_signal/example-config.yaml
mautrix_signal/portal.py

Converts an m.location event to a map link in order to bridge it to signal. Let's you choose the map provider via config setting.
I ran into a bit of a problem with the different fields that provide additional information. `content.body` is supposed to be able to contain a description. Element just copies the `content.geo_uri` field there, which isn't adding anything of value, so it shouldn't be printed. `content.body` also contains relay sender information after the relay format is applied, so I can't exclude the field. I opted for removing the contents of `geo_uri` from `body` before prepending it, since that seemed to be the solution with the least amount of change.
This doesn't include msc3488. I'm not really sure how to account for that because I still need `body` in relay mode. But …

Bridge Matrix -> Signal location

---

mautrix_signal/commands/signal.py
mautrix_signal/portal.py
mautrix_signal/util/__init__.py
mautrix_signal/util/user_has_power_level.py

I have added the commands for getting the id of a room and bridging an existing room to an existing signal group

Add bridge and get_id commands

---

mautrix_signal/portal.py
mautrix_signal/puppet.py

This sets the topic of a DM to the Signal user's phone number.
It also handles a change of phone number (since apparently signal is able to do that)

set Signal user's phone number as topic in DMs

---

mautrix_signal/commands/signal.py
mautrix_signal/matrix.py
mautrix_signal/portal.py

This PR bridges join rules from matrix to signal and vice versa.
`restricted` is bridged as `ADMINISTRATOR`, which is the same as for `knock`.
I was considering for a while whether it should be `ANY` (the bridge bot can invite puppets that don't match the restrictions and joining the signal group from matrix will work) or `UNSATISFIABLE` (A matrix user setting the join rules to `restricted` would probably not want random signal users to join if they don't correspond to the restrictions).
I decided that probably emulating `restricted` for the signal side through a relay is the best course of action, because it produces expected behavior on the matrix side and does not cause problems on the signal side. The only downside is that a relay would be required even if only logged-in users are in …

Bridge join rules (both ways)

---

mautrix_signal/config.py
mautrix_signal/example-config.yaml
mautrix_signal/portal.py

This PR allows users to set a dedicated relaybot user. When the relaybot is invited, it will automatically be set as the relay. This way, users no longer need to log in with the relaybot account to run set-relay manually. The relaybot can be shared between users more easily.

add relaybot config option and auto-set relay for relaybot

---

mautrix_signal/commands/signal.py
mautrix_signal/portal.py

- move relaybot invite handling to separate function
- also set relaybot as relay when creating a new portal. I don't find the check for the bot in the for loop particularly pretty, but it seemed to be the most efficient option.
- also fixes a bug that breaks group creation because join_rule isn't passed by get_initial state.

set relaybot as relay on create

---

mautrix_signal/signal.py

it looks like these are things like typing notifications, and read receipts

AND-4424: don't show error messages on decryption failure for IMPLICIT messages

---

ROADMAP.md
mausignald/signald.py
mautrix_signal/matrix.py
mautrix_signal/portal.py

Joining via invite link if the link policy is `ADMINISTRATOR` and the join_rule is `knock` will trigger a knock. The knock may then be accepted, which causes the signal user to be accepted into the group and join the matrix room.
- I was unable to test rejecting knocks, because I don't have a client that supports rejecting knocks. I'm quite confident that the code is correct though.
- requires https://github.com/mautrix/python/pull/105 (I see it was just merged)
- this PR only really makes sense with https://github.com/mautrix/signal/pull/268, to ensure that link policy and join_rule match, but it shouldn't cause any issues if they don't. Join requests just won't work in that case.
One problem is that join requests are not pushed as a message on signal, but have to be fetched by the …

Bridge join via invite link to knock (Signal->Matrix), bridge ban/unban (Signal-> Matrix)

---

mautrix_signal/commands/signal.py
mautrix_signal/config.py
mautrix_signal/example-config.yaml
mautrix_signal/portal.py

Invite a user by typing `!signal invite <phone>` in a bridged room.
Since this is primarily intended for rooms bridged across several platforms for a user of another platform to invite a signal user, I also added relay support for invites. Relaying invites can be disabled in the config. I made the default `true`, because I believe this is expected functionality. In particular if a non-logged-in user invites a logged-in-user, they don't expect them to be kicked by the bridge bot on the next sync.

add invite command, enable relay for invites

---

mausignald/types.py
mautrix_signal/portal.py
mautrix_signal/signal.py
mautrix_signal/user.py

Getting a puppet for a double-puppeted user returns the user, if double puppeting is not enabled, it will only return their puppet. This caused non-double-puppeted users to not receive appropriate power level for their account.
This PR also cleans up a few loosely related things:
1. All remaining GroupV1 support is removed (hopefully)
2. ChatInfo is now limited to full group info, GroupV2ID is not allowed. I also replaced ChatInfo by GroupV2 in some places. Using ChatInfo for both GroupV2 and GroupV2ID made it necessary to always check for full group info and pass a source to obtain full group info, even if that ended up never being used. I suppose the same is true for Profile and Address, but they're just used a lot less, so it's less annoying

fix power level assignment for non-double-puppeted users, some cleanup

---

ROADMAP.md
mautrix_signal/commands/signal.py
mautrix_signal/commands/util.py
mautrix_signal/config.py
mautrix_signal/example-config.yaml
mautrix_signal/matrix.py
mautrix_signal/portal.py

Auto create group

---

mausignald/errors.py
mautrix_signal/portal.py

The bridge used to kick newly invited signal ghosts upon error, even if that error just meant that they already are in the group.
I encountered that error when testing the mautrix-python PR. When the group is created, all users in the room at that moment are added to the group, invites that have gone through on the matrix side at the time of group creation will produce a GroupPatchNotAcceptedError. The bridge should not kick the user if they are confirmed to be in the group.

don't kick ghost on GroupPatchNotAcceptedError if they are in the signal group

---

mautrix_signal/commands/auth.py

This helps getting rid of stale users, who no longer use their matrix account.
I thought of adding an optional parameter to the `logout` command, but I didn't know how to make that bit admin only (and also not require auth). So a separate command made more sense.

add command to let admins log out users

---

mausignald/errors.py
mausignald/signald.py
mautrix_signal/commands/signal.py
mautrix_signal/portal.py
mautrix_signal/user.py

This is still entirely untested since I would need a ProofRequiredError to do so. I am not currently commited enough to try and trigger one for my Signal account, but anyone who has one, please try. Or if you find obvious mistakes without testing, let me know.
I've noticed that ProofRequiredError rarely comes in the SendMessageResult, but usually as a ResponseError, so I created another ProofRequiredException in errors.py. I didn't know how to reconcile the two, since SendMessageResult probably wouldn't work with an Exception instead of a SerializableAttrs, but I also needed to inherit from ResponseError.
When portal.handle_matrix_message() encounters a ProofRequiredError, it should store a token in the respective user, so the user won't have to copy&paste that. Since tokens are temporary …

Add ProofRequiredError Exception and submit-challenge command

---

commands.go
config/bridge.go
config/upgrade.go
example-config.yaml
messagetracking.go
portal.go
user.go

I currently don't have time for thorough testing & cleanup, but I have been able to relay a message to Signal.
Please give this a whirl if you have time. I will otherwise do thorough testing and cleanup at some later point.

add relay mode

---

commands.go
custompuppet.go
database/database.go
database/disappearingmessage.go
database/lostportal.go
database/message.go
database/portal.go
database/puppet.go
database/reaction.go
database/upgrades/00-latest.sql
database/upgrades/16-refactor-postgres.sql
database/upgrades/17-refactor-sqlite.sql
database/user.go
disappearing.go
main.go
msgconv/matrixfmt/convert_test.go
msgconv/matrixfmt/html.go
msgconv/signalfmt/convert.go
msgconv/signalfmt/convert_test.go
msgconv/signalfmt/tags.go
pkg/signalmeow/events/message.go
pkg/signalmeow/incoming_messages.go
pkg/signalmeow/receiving.go
pkg/signalmeow/sending.go
portal.go
provisioning.go
puppet.go
user.go

* Change most columns to `NOT NULL`, including primary keys (because SQLite).
* Change columns only storing signal user IDs (portal receiver, message sender, user uuid) to use the `uuid` type instead of `TEXT`.
* Drop chat ID from message table primary key.
* Add part index to message table to replace timestamp hack for storing multiple parts of the same message.
* Change query wrappers to use new QureyHelper struct in dbutil, and pass contexts and errors everywhere.
As a part of changing the portal receiver from phone number to uuid, old portals whose receiver isn't logged in anymore may be discarded. The discarded portals will be stored in the lost_portals table for cleanup or recovery.

Refactor database tables and query wrappers

---

go.mod
go.sum
main.go
messagetracking.go
msgconv/from-matrix.go
msgconv/from-signal.go
msgconv/urlpreview.go
pkg/signalmeow/attachments.go
pkg/signalmeow/device.go
pkg/signalmeow/groups.go
pkg/signalmeow/keys.go
pkg/signalmeow/profile.go
pkg/signalmeow/provisioning.go
pkg/signalmeow/receiving.go
pkg/signalmeow/sending.go
pkg/signalmeow/web/signalwebsocket.go
pkg/signalmeow/web/web.go
portal.go
provisioning.go
user.go

- provisioning: use libserv instead of custom logger
- provisioning: use proper context key
- provisioning: don't send resolve identifier response fields if nil
- signalmeow: use structured logging
- provisioning: use structured logging
- zerolog: remove instances of using global log
- user: use structured logging
- main: use structured logging

logging: use structured logging in more places

---

portal.go

because if a user ever leaves a portal, there is no obvious way for them to rejoin it.
This restores 468f655, which was lost during a refactor.

Ensure user is invited to portals on update

---

portal.go

Otherwise, the bridge crashes when it sees a reaction from Signal.
---
This fixes a crash introduced by 666ccf1.

Avoid nil dereference on existing reaction lookup

---

config/bridge.go
config/upgrade.go
example-config.yaml
pkg/libsignalgo/verifysignature.go
pkg/signalmeow/groups.go
portal.go

There is more to come, but this part should already work.
What's missing is kicking Users. It currently only kicks the User's puppet.
Another problem is that mautrix-signal doesn't set room permissions and power levels correctly yet, so some actions have to be performed by the bridge bot. Make sure to give yourself appropriate permissions through `set-pl` before testing.
Also includes a fix where the avatar was not set if there wasn't one to begin with.

handle Group Change

---

commands.go
pkg/signalmeow/groups.go
pkg/signalmeow/sending.go

This seems to be the proper way to inform other participants/devices about the group being created

send empty groupv2context instead of empty group change

---

pkg/signalmeow/groups.go
portal.go

I was hoping fetching group history would help with correct metadata during portal creation but (obviously, probably) it only allows you to fetch revisions from when a user was added.
Might still come in handy for more than just handling missed group changes, which shouldn't ever happen anyway.

Handle missed GroupChanges using group history

---

pkg/signalmeow/events/message.go
pkg/signalmeow/receiving.go
user.go

We were falling through without propagating errors anywhere. I caught most decryption errors and send them along in the new Err field in DecryptionResult, to be then passed along to the bridge as a new type of chat event.
I'm going to do another pass to catch any last decryption errors, but this should be a big improvement over what we currently do.

Minor incoming messages refactor and send m.notice on decryption errors

---

pkg/signalmeow/client.go
pkg/signalmeow/keys.go
pkg/signalmeow/receiving.go

Currently the disconnect/stop bridge call will complete before all the loops have returned. This switches them all to use a shared cancelable context and wait group to block on stop until all loops exit.

Block until stop completes

---

pkg/libsignalgo/serviceid_clang.go
pkg/libsignalgo/serviceid_gcc.go

The workaround for https://github.com/golang/go/issues/7270 is seemingly being applied to ARM64 Windows, wherein we use [the llvm-mingw toolchain](https://github.com/mstorsjo/llvm-mingw). This breaks the build:
> ...\authcredential.go:54:3: cannot use NewACIServiceID(aci).CFixedBytes() (value of pointer type cPNIType) as *_Ctype_SignalServiceIdFixedWidthBinaryBytes value in variable declaration
> ...\authcredential.go:55:3: cannot use NewPNIServiceID(pni).CFixedBytes() (value of pointer type cPNIType) as *_Ctype_SignalServiceIdFixedWidthBinaryBytes value in variable declaration

build: use `serviceid_clang.go` when building for arm64 windows
