mautrix/signal

mautrix_signal/commands/signal.py
Also made the phone number (hopefully) optional if in a portal
=> Make verify code work without signal bot

mautrix_signal/config.py, mautrix_signal/example-config.yaml, mautrix_signal/matrix.py, mautrix_signal/portal.py, mautrix_signal/user.py
checks in `portal.py` in `def handle_matrix_message` if relaybot function is enabled and calls  `def _handle_matrix_message` as regular function
=> Add relaybot functionality for bridge user

mausignald/types.py, mautrix_signal/signal.py
=> calls: show notifications for call start/end in DMs

mausignald/signald.py, mautrix_signal/config.py, mautrix_signal/example-config.yaml, mautrix_signal/user.py, mautrix_signal/web/provisioning_api.py
Requires https://gitlab.com/beeper/signald/-/merge_requests/12.
=> login: use wait_for_scan to figure out when the user scans the QR code

mausignald/rpc.py, mausignald/signald.py, mautrix_signal/portal.py
=> rpc: add logging to correlate Matrix event ID to signald request ID

mautrix_signal/portal.py
Fixes issue where changing your reaction rapidly could cause the old reaction to not be redacted properly.
=> reactions: fix concurrency bug

mautrix_signal/matrix.py, mautrix_signal/portal.py, mautrix_signal/user.py, mautrix_signal/web/provisioning_api.py
This commit adds a utility function for helping to deal with auth failures and uses it around the codebase.
=> handle authorization failures in more places

mausignald/signald.py, mausignald/types.py, mautrix_signal/portal.py
Uses the `com.beeper.linkpreviews` key.
=> link previews: support Signal <-> Beeper

mausignald/types.py, mautrix_signal/portal.py, mautrix_signal/signal.py
=> signal kicks: handle being kicked from Signal group

mautrix_signal/__main__.py, mautrix_signal/config.py, mautrix_signal/example-config.yaml, mautrix_signal/web/provisioning_api.py, mautrix_signal/web/segment_analytics.py
=> segment: add tracking for provisioning API

Dockerfile, docker-run.sh
associated signald change incoming
=> fix docker user

mausignald/signald.py, mautrix_signal/config.py, mautrix_signal/example-config.yaml, mautrix_signal/portal.py
This seems to work. Please take a look.
But I don't really know python, I mostly used copy & paste and common sense. I also don't know what possible issues to test for.
=> Leave group

mautrix_signal/commands/signal.py
mautrix-signal currently just prints a stack trace. This PR prints legible a "user not registered" notice instead.
=> catch unregistered user error and print readable notice

mautrix_signal/config.py, mautrix_signal/example-config.yaml, mautrix_signal/portal.py, requirements.txt
Requires https://github.com/mautrix/python/pull/106
=> encryption: add ability to control rotation settings

mausignald/types.py, mautrix_signal/puppet.py, mautrix_signal/web/provisioning_api.py
Requires https://gitlab.com/signald/signald/-/merge_requests/148
Signed-off-by: Sumner Evans <sumner@beeper.com>
=> contact names: use new contact_name field instead of name

mausignald/errors.py, mautrix_signal/commands/auth.py
Tested successfully. The previous --captcha flag still works.
=> catch captcha required error and request user to enter captcha

mautrix_signal/commands/auth.py
My MR had uncommitted changes.
Apologies.
=> fix evt.sender.command_status

mautrix_signal/db/message.py, mautrix_signal/matrix.py
Signed-off-by: Sumner Evans <sumner@beeper.com>
=> read receipts: send to latest message before receipt ts if eventID is not a message

mausignald/signald.py, mautrix_signal/commands/auth.py
=> Command: Add linked device

mautrix_signal/user.py
Signed-off-by: Sumner Evans <sumner@beeper.com>
=> bridge state: delay reporting CONNECTING state

mausignald/errors.py, mausignald/signald.py, mautrix_signal/signal.py, mautrix_signal/user.py, mautrix_signal/web/provisioning_api.py
Corresponding signald change: https://github.com/beeper/signald/pull/1
=> provisioning: fix logout and relogin

go.mod, go.sum, provisioning.go
* use libserv
* use proper context key
* fix resolve identifier response fields
Signed-off-by: Sumner Evans <me@sumnerevans.com>
=> provisioning: cleanup

.pre-commit-config.yaml, commands.go, disappearing.go, messagetracking.go, portal.go, provisioning.go, puppet.go, user.go
Signed-off-by: Sumner Evans <me@sumnerevans.com>
=> pre-commit: use Stringer(x, y) intsead of Str(x, y.String())

pkg/libsignalgo/groupsecretparams.go, pkg/signalmeow/groups.go, pkg/signalmeow/keys.go, pkg/signalmeow/provisioning.go, pkg/signalmeow/sending.go, pkg/signalmeow/store/device.go, portal.go
Signed-off-by: Sumner Evans <me@sumnerevans.com>
=> treewide: fix all ignored errors

commands.go, database/userportal.go, disappearing.go, main.go, messagetracking.go, pkg/signalmeow/contact.go, pkg/signalmeow/receiving.go, portal.go, provisioning.go, user.go
Satisfies the "zerolog-use-stringer" pre-commit hook
=> Use Stringer with zerolog

Dockerfile, Makefile, build-go.sh, build-rust.sh, docker-run.sh
Restore the effects of edf04da that were lost in 6e7faa2
=> Restore debug build & remote debugging for Docker builds

ROADMAP.md, pkg/signalmeow/groups.go, portal.go
This seems to do what it's supposed to do, although I could probably test more extensively
=> Update group info

example-config.yaml
Micro fix to the example config
=> Fix !wa => !signal in example-config.yaml

metrics.go, portal.go, user.go
=> Restore missing metrics & remove unused ones

commands.go, pkg/libsignalgo/groupsecretparams.go, pkg/signalmeow/groups.go, pkg/signalmeow/sending.go, portal.go
Also send group updates to pendingMembers
=> UUID->ServiceID & invite command

pkg/libsignalgo/profilekey.go, pkg/signalmeow/groups.go
So far untested, need tester with corresponding error (doesn't seem to be causing new breakage)
=> try fix zero length UserId error

config/bridge.go, config/upgrade.go, example-config.yaml, msgconv/from-matrix.go, msgconv/msgconv.go, portal.go
=> add support for matrix -> signal location messages

msgconv/from-signal.go
=> Properly convert signal long text messages

portal.go
I had a puppet invited but not joined and couldn't figure out why
=> log more errors for addmember

commands.go
changed sync-space to support both space sync and group sync. I hope it's OK that it uses two loops rather than one.
=> Sync groups command

pkg/connector/groupinfo.go, pkg/signalmeow/store/container.go
I wasn't able to test this due to lack of new contacts, but it's mostly copied over from #501  so it should work all the same
=> Look up ACIs for PNIs

pkg/connector/groupinfo.go
I noticed this was missing but I can't test now due to lack of new contacts.
Is there anything that can go wrong?
=> handle PromotePending(PniAci)Members

pkg/connector/handlematrix.go, pkg/signalid/ids.go
=> v2: matrix -> signal power levels

pkg/connector/chatinfo.go, pkg/connector/client.go, pkg/signalmeow/contact.go, pkg/signalmeow/profile.go
=> client: immediately sync DM ghosts when viewed

go.mod, go.sum, pkg/connector/capabilities.go, pkg/connector/chatinfo.go, pkg/connector/groupinfo.go, pkg/connector/handlematrix.go, pkg/signalmeow/attachments.go, pkg/signalmeow/groups.go, pkg/signalmeow/profile.go
It's throwing a bad request which means something broke (or was already broken)
=> startchat: add support for creating groups
